Remove output to logs
scylladb/scylla-ansible-roles pull request #135
Opened 2022-06-30 12:02 UTC by jbragdon1

This task seems to dump username / password / auth token to the outputted logs. Adding a no_log: true will still show the task running, but remove a great deal of the output.

Tested in a local copy

2025-05-14 14:56 UTC, vladzcloudius commented
Was going over the "deserted PRs" (sorry, @jbragdon1).
@vreniers this is an interesting one.

2025-05-14 14:57 UTC, vladzcloudius requested changes

2025-05-14 14:57 UTC, vladzcloudius commented on ansible-scylla-manager/tasks/add-clusters.yml
> +  no_log: true
I'd parametrize it. And set it to `False` by default to preserve the current behavior.

2025-05-15 06:41 UTC, vreniers commented on ansible-scylla-manager/tasks/add-clusters.yml
This PR requires a rebase. The file name was changed to `add_cluster.yml`.

2026-07-01 07:19 UTC, vreniers commented
I think we can make a broader issue out of this. 
The same happens with starting monitoring, or where cqlsh is used. We can hide those from the logs of course.

 I've opened an internal JIRA https://scylladb.atlassian.net/browse/ANSROLES-15 to track it. 

Since there was no reply or activity on this PR - I'll be closing it.

2026-07-01 07:19 UTC, closed without merging