scylla-node: remove ignore_errors, make node exporter from 2022 work
scylladb/scylla-ansible-roles pull request #324
Opened 2024-01-08 16:56 UTC by tarzanek

2022 node exporter now works for clean install and upgrades

fix detection of node-exporter services

make sure the name of node exporter service matches the check

2024-01-08 16:57 UTC, tarzanek commented
I split away node exporter from https://github.com/scylladb/scylla-ansible-roles/pull/232

can you review @vladzcloudius or @igorribeiroduarte / @ebenzecri  ?

2024-01-09 22:39 UTC, tarzanek commented
don't merge, I am trying to fix molecule

2024-02-28 17:28 UTC, tarzanek commented
ok, molecule should pass now
@igorribeiroduarte @vladzcloudius this is just extract of reviewed and tested commit from https://github.com/scylladb/scylla-ansible-roles/pull/232

so please re-review, or check above, this will get rid of ignore errors for node exporter and properly use it for any version now

2024-03-12 18:15 UTC, tarzanek commented
@vladzcloudius ping?

2024-03-15 22:33 UTC, vladzcloudius requested changes

2024-03-15 22:33 UTC, vladzcloudius commented on ansible-scylla-node/tasks/main.yml
> +  ansible.builtin.service_facts:
Unrelated

2024-03-15 22:33 UTC, vladzcloudius commented
This PR has conflicts, please, rebase.

2024-03-18 17:07 UTC, tarzanek commented on ansible-scylla-node/tasks/main.yml
> +  ansible.builtin.service_facts:
removed

2024-03-18 17:07 UTC, tarzanek commented
rebased, but logic changed, I need to retest new condition

```
  when: (install_type == 'online') and (node_exporter_install.stat.exists) and ((scylla_package_prefix + '-node-exporter') not in ansible_facts.packages)

```

2026-07-01 18:59 UTC, closed without merging