update gpg keys for new Scylla versions
scylladb/scylla-ansible-roles pull request #369
Opened 2024-03-19 09:37 UTC by tarzanek

fixes #334

2024-03-27 19:56 UTC, vladzcloudius requested changes
Please, specify the component (ansible-scylla-node) in the patch description.

2024-04-05 10:27 UTC, tarzanek commented
@vladzcloudius fixed, please re-review

2024-05-18 17:21 UTC, tarzanek commented
@vladzcloudius ping

2024-06-24 17:59 UTC, vladzcloudius approved these changes

2024-06-24 17:59 UTC, merged