ansible-scylla-node: auto-detect NVMe: only use non-partitioned disks.
scylladb/scylla-ansible-roles pull request #413
Opened 2024-10-11 12:24 UTC by vreniers

NVMe disks should only be selected that are not in use, which should be the case when they are not partitioned.

Fixes #407

2024-10-23 11:09 UTC, igorribeiroduarte submitted a review, later dismissed

2024-11-05 10:37 UTC, tarzanek commented on ansible-scylla-node/tasks/common.yml
> +          { echo -n "/dev/$nvme_disk "; lsblk "/dev/$nvme_disk" -o MOUNTPOINT | grep / | wc -l; } | awk '{if ($2=="0") print $1}'
lsblk -n ?
to void printing header ?

2025-01-27 17:51 UTC, vladzcloudius commented
> ```
>   lsblk -oNAME,PATH,PTTYPE,MOUNTPOINT -nd | grep nvme | awk '{if ($3=="" && $4=="") print $2}'
> ```
> 
> misbehaves on md0 with multiple nvmes

What do you mean exactly, @tarzanek ?
Please, provide the corresponding output so that we can all see what's the problem.

2025-01-27 17:51 UTC, vladzcloudius requested changes

2025-01-27 17:51 UTC, vladzcloudius commented on ansible-scylla-node/tasks/common.yml
> +        for nvme_disk in $(lsblk -oNAME -nd | grep nvme)
Is there a strong guarantee that NVME disks are always going to have an 'nvme' in their name in the output of `lsblk`?

2025-01-28 13:15 UTC, vreniers commented on ansible-scylla-node/tasks/common.yml
> +        for nvme_disk in $(lsblk -oNAME -nd | grep nvme)
It is the case for AWS, GCP and Azure. Regardless, that should be part of parameter documentation as this is the expectation.

2025-01-28 13:29 UTC, vladzcloudius commented on ansible-scylla-node/tasks/common.yml
> +        for nvme_disk in $(lsblk -oNAME -nd | grep nvme)
The question wasn't about infra - it's an OS question. Linux to be specific. And I don't think there is such a guarantee.
I don't see any reason not to continue using the `nvme` utility which does provide you all required guarantees.

2025-01-28 14:27 UTC, vreniers commented on ansible-scylla-node/tasks/common.yml
> +        for nvme_disk in $(lsblk -oNAME -nd | grep nvme)
Adjusted.

2025-01-28 14:29 UTC, vladzcloudius approved these changes

2025-01-28 16:40 UTC, merged